/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.codingshuttle.ecommerce.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderStatusUpdatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2926780877381105861L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderStatusUpdatedEvent\",\"namespace\":\"com.codingshuttle.ecommerce.events\",\"fields\":[{\"name\":\"orderId\",\"type\":\"long\",\"default\":0},{\"name\":\"orderStatus\",\"type\":\"string\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderStatusUpdatedEvent> ENCODER =
      new BinaryMessageEncoder<OrderStatusUpdatedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderStatusUpdatedEvent> DECODER =
      new BinaryMessageDecoder<OrderStatusUpdatedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OrderStatusUpdatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OrderStatusUpdatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderStatusUpdatedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OrderStatusUpdatedEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OrderStatusUpdatedEvent from a ByteBuffer. */
  public static OrderStatusUpdatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long orderId;
  @Deprecated public java.lang.CharSequence orderStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderStatusUpdatedEvent() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param orderStatus The new value for orderStatus
   */
  public OrderStatusUpdatedEvent(java.lang.Long orderId, java.lang.CharSequence orderStatus) {
    this.orderId = orderId;
    this.orderStatus = orderStatus;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return orderStatus;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.Long)value$; break;
    case 1: orderStatus = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.Long getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.Long value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'orderStatus' field.
   * @return The value of the 'orderStatus' field.
   */
  public java.lang.CharSequence getOrderStatus() {
    return orderStatus;
  }

  /**
   * Sets the value of the 'orderStatus' field.
   * @param value the value to set.
   */
  public void setOrderStatus(java.lang.CharSequence value) {
    this.orderStatus = value;
  }

  /**
   * Creates a new OrderStatusUpdatedEvent RecordBuilder.
   * @return A new OrderStatusUpdatedEvent RecordBuilder
   */
  public static com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder newBuilder() {
    return new com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder();
  }

  /**
   * Creates a new OrderStatusUpdatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderStatusUpdatedEvent RecordBuilder
   */
  public static com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder newBuilder(com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder other) {
    return new com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder(other);
  }

  /**
   * Creates a new OrderStatusUpdatedEvent RecordBuilder by copying an existing OrderStatusUpdatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new OrderStatusUpdatedEvent RecordBuilder
   */
  public static com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder newBuilder(com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent other) {
    return new com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder(other);
  }

  /**
   * RecordBuilder for OrderStatusUpdatedEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderStatusUpdatedEvent>
    implements org.apache.avro.data.RecordBuilder<OrderStatusUpdatedEvent> {

    private long orderId;
    private java.lang.CharSequence orderStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderStatus)) {
        this.orderStatus = data().deepCopy(fields()[1].schema(), other.orderStatus);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OrderStatusUpdatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderStatus)) {
        this.orderStatus = data().deepCopy(fields()[1].schema(), other.orderStatus);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.Long getOrderId() {
      return orderId;
    }

    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder setOrderId(long value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder clearOrderId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderStatus' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderStatus() {
      return orderStatus;
    }

    /**
      * Sets the value of the 'orderStatus' field.
      * @param value The value of 'orderStatus'.
      * @return This builder.
      */
    public com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder setOrderStatus(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.orderStatus = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderStatus' field has been set.
      * @return True if the 'orderStatus' field has been set, false otherwise.
      */
    public boolean hasOrderStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderStatus' field.
      * @return This builder.
      */
    public com.codingshuttle.ecommerce.events.OrderStatusUpdatedEvent.Builder clearOrderStatus() {
      orderStatus = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderStatusUpdatedEvent build() {
      try {
        OrderStatusUpdatedEvent record = new OrderStatusUpdatedEvent();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.Long) defaultValue(fields()[0]);
        record.orderStatus = fieldSetFlags()[1] ? this.orderStatus : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderStatusUpdatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderStatusUpdatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderStatusUpdatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<OrderStatusUpdatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
