spring.application.name=order-service

server.servlet.context-path=/orders
server.port=9021

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/orderDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost